version: "3.9"

services:
  stable-diffusion-webui:
    image: abdbarho/stable-diffusion-webui:latest
    container_name: stable-diffusion-webui
    environment:
      - CLI_ARGS=--skip-torch-cuda-test
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - stable-diffusion-models:/models
      - ./outputs:/outputs
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

volumes:
  stable-diffusion-models:
